# This list of products will replace any occurrence of `<product>`
# in a variable-definition yaml file


#   i.e., The following standard structure in economic variables:
#   Consumption|Households|< product >|Imported:
#   Consumption|Government|< product >|Domestic:

<Product>:
  pAGRI:
    description: 'Agriculture'

  pINDU:
    description: 'Manufacturing industry'

  pALUM:
    description: 'Aluminium production'

  pSERV:
    description: 'Services'

  pTRAN:
    description: 'Transport services'

  pELEC:
    description: 'Electricity'

  pTRDI:
    description: 'Trade and distribution services of electricity'

  pHTWT:
    description: 'Steam and hot water supply'

  pOIL:
    description: 'Crude Oil'

  pGSL:
    description: 'Gasoline'

  pDSL:
    description: 'Diesel'

  pHDI:
    description: 'Heavy distillate'

  pNG:
    description: 'Natural gas'

  pCOA:
    description: 'Coal'

  pBIO:
    description: 'Biofuels'

  pFUL:
    description: 'Other fuels'

  pH2:
    description: 'Hydrogen'
